modLoader="javafml"
loaderVersion="[50,)"
license="MIT"

[[mods]]
modId="finn_mod"
version="1.0"
displayName="Finn Mod"
description="A custom modded dog based on Finn."
authors="Ian Baime"
credits="Special thanks to Finn."